### ISSUE TITLE
add sandbox setup instructions using flextesa

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/tezedge-client#3]
1 - install tezos-client: https://assets.tqtezos.com/docs/setup/1-tezos-client/

2 - install the docker image to run tezos sandbox: https://assets.tqtezos.com/docs/setup/2-sandbox/

**Comment by marsella** [comment]
What is the status of this issue? We include links to this documentation in the README.

**Comment by jakinyele** [comment]
@marsella Ok, great. I think we can close this issue then.
